In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.

    Arguments:
    x -- A scalar or numpy array.

    Return:
    s -- sigmoid(x)
    """

    #sigmoid, s(x) = 1 / (1 + (e^(-x)))
    
    s = 1 / (1 + np.exp(-x))

    return s


def sigmoid_grad(s):
    """
    Compute the gradient for the sigmoid function here. Note that
    for this implementation, the input s should be the sigmoid
    function value of your original input x.

    Arguments:
    s -- A scalar or numpy array.

    Return:
    ds -- Your computed gradient.
    """
    
    '''
             s =       1
                 -----------------             
                   1 + (e^(-x))
                   
             ds =      1                           *   d
                  [{ -----------------} ^ 2 ]        ----- (  1 + (e^(-x)) ) 
                    1 + (e^(-x))                       dx
         
    '''
    ds = s * (1 - s)

    return ds



In [7]:
x = np.array([[3, 4], [5, -6]])
f = sigmoid(x)
g = sigmoid_grad(f)

In [8]:
x

array([[ 3,  4],
       [ 5, -6]])

In [9]:
f

array([[ 0.95257413,  0.98201379],
       [ 0.99330715,  0.00247262]])

In [10]:
g

array([[ 0.04517666,  0.01766271],
       [ 0.00664806,  0.00246651]])